# Generated by Django 4.2.13 on 2024-06-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('centername', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fathername', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mothername', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('medium', models.CharField(choices=[('EN', 'English'), ('ML', 'Malayalam')], default='EN', max_length=10)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center')),
            ],
        ),
    ]
