# Generated by Django 4.2.13 on 2024-06-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_email_alter_userprofile_fathername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
