# Generated by Django 4.2.13 on 2024-06-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='medium',
            field=models.CharField(choices=[('EN', 'English'), ('ML', 'Malayalam')], max_length=10),
        ),
    ]
